### ISSUE TITLE
urlparse error : Port could not be cast to integer value

### ISSUE THREAD

**Issue by Stefal** [Stefal/rtkbase#364]
**Describe the bug**

non blocking error in server.py

```
Feb 03 12:33:45 basegnss python[2244]: [2024-02-03 12:33:45,576] ERROR in app: Exception on / [HEAD]
Feb 03 12:33:45 basegnss python[2244]: Traceback (most recent call last):
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
Feb 03 12:33:45 basegnss python[2244]: response = self.full_dispatch_request()
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
Feb 03 12:33:45 basegnss python[2244]: rv = self.handle_user_exception(e)
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
Feb 03 12:33:45 basegnss python[2244]: rv = self.dispatch_request()
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
Feb 03 12:33:45 basegnss python[2244]: return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/flask_login/utils.py", line 285, in decorated_view
Feb 03 12:33:45 basegnss python[2244]: return current_app.login_manager.unauthorized()
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 196, in unauthorized
Feb 03 12:33:45 basegnss python[2244]: redirect_url = make_login_url(login_view, next_url=request.url)
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 106, in __get__
Feb 03 12:33:45 basegnss python[2244]: value = self.fget(obj) # type: ignore
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/werkzeug/sansio/request.py", line 210, in url
Feb 03 12:33:45 basegnss python[2244]: return get_current_url(
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/werkzeug/sansio/utils.py", line 137, in get_current_url
Feb 03 12:33:45 basegnss python[2244]: return uri_to_iri("".join(url))
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/home/basegnss/rtkbase/venv/lib/python3.11/site-packages/werkzeug/urls.py", line 97, in uri_to_iri
Feb 03 12:33:45 basegnss python[2244]: if parts.port:
Feb 03 12:33:45 basegnss python[2244]: ^^^^^^^^^^
Feb 03 12:33:45 basegnss python[2244]: File "/usr/lib/python3.11/urllib/parse.py", line 173, in port
Feb 03 12:33:45 basegnss python[2244]: raise ValueError(f"Port could not be cast to integer value as {port!r}")
Feb 03 12:33:45 basegnss python[2244]: ValueError: Port could not be cast to integer value as ':ffff:192.168.1.47'
```

**To Reproduce**
I don't know how to reproduce

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.5.0

**Comment by Stefal** [comment]
fixed in release 2.6.0 (switch to gunicorn server)
